blank_issues_enabled: false
contact_links:
    - name: 🚨 Report Security Vulnerability
      url: https://github.com/Astrotomic/.github#security
      about: Please report security vulnerabilities by email to dev@astrotomic.info
